python train.py \
  -b 1 \
  -e 1 \
  -l 0.001 \
  -r 500 \
  -n 'test_Varnet' \
  -t '/home/Data2/train/' \
  -v '/home/Data2/val/' \
  --cascade 35 \
  --chans 18 \
  --sens_chans 8 \
  --aug_on \
  --aug_schedule exp \
  --aug_delay 10 \
  --aug_strength 0.5 \
  --aug_exp_decay 3.0 \
